name: Swift Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: apple/setup-xcode@v2  # Utilisez la référence complète avec le nom du propriétaire du référentiel
      with:
        xcode-version: '13.2'  # Spécifiez la version d'Xcode que vous souhaitez utiliser

    - name: Install Dependencies
      run: |
        swift package resolve

    - name: Build and Test
      run: |
        xcodebuild clean build test \
          -workspace YourApp.xcworkspace \
          -scheme YourApp \
          -destination 'platform=iOS Simulator,OS=17.0,name=iPhone 13'  # Spécifiez la version iOS et l'appareil que vous souhaitez tester
